{% set name = "genutil" %}
{% set version = "3.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/UV-CDAT/genutil/archive/v{{ version }}.tar.gz
    sha256: 1df22b07375f26fd6f687d5c0df1cbfeda8cc85b775720def7e69c06f7372b56
    

build:
  number: 0
  skip: True  # [win or py3k]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - udunits2
    - toolchain  # [osx]
  run:
    - python
    - cdms2
    - numpy x.x
    - udunits2

test:
    command:
        - export UVCDAT_ANONYMOUS_LOG=false && python run_tests.py -v2

about:
    home:  http://gitub.com/UV-CDAT/genutil
    license: 'CCLRC'
    summary: 'General Utitilites for the Community Data Analysys Tools'

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
